#ifndef MODEL_BUILDER_HPP
#define MODEL_BUILDER_HPP

#include "pinocchio/algorithm/model.hpp"
#include "pinocchio/parsers/urdf.hpp"
// auto-generated by generate_parameter_library
#include "cpcc2_tiago_parameters.hpp"

using namespace pinocchio;
using namespace Eigen;

namespace model_builder {
Model build_model(std::vector<std::string> joints);
}  // namespace model_builder

#endif  // MODEL_BUILDER_HPP