#ifndef MODEL_BUILDER_HPP
#define MODEL_BUILDER_HPP

#include <Eigen/Dense>

#include "pinocchio/algorithm/model.hpp"
#include "pinocchio/multibody/data.hpp"
#include "pinocchio/multibody/model.hpp"
#include "pinocchio/parsers/urdf.hpp"
#include <pinocchio/algorithm/compute-all-terms.hpp>
#include <pinocchio/algorithm/frames.hpp>
#include <pinocchio/algorithm/model.hpp>
#include <pinocchio/fwd.hpp>
#include <pinocchio/spatial/se3.hpp>

// auto-generated by generate_parameter_library
#include "cpcc2_tiago_parameters.hpp"

using namespace pinocchio;

namespace model_builder {
Model build_model(std::vector<std::string> joints);
void updateReducedModel(const Eigen::Ref<const Eigen::VectorXd> &x,
                        Model &rmodel, Data &rdata);
SE3 get_end_effector_SE3(Data &rdata, FrameIndex &end_effector_id);
} // namespace model_builder

#endif // MODEL_BUILDER_HPP