#ifndef MODEL_BUILDER_HPP
#define MODEL_BUILDER_HPP

#include <Eigen/Dense>
#include <filesystem>

#include "pinocchio/algorithm/compute-all-terms.hpp"
#include "pinocchio/algorithm/frames.hpp"
#include "pinocchio/algorithm/model.hpp"
#include "pinocchio/fwd.hpp"
#include "pinocchio/multibody/data.hpp"
#include "pinocchio/multibody/model.hpp"
#include "pinocchio/parsers/urdf.hpp"
#include "pinocchio/spatial/se3.hpp"

// auto-generated by generate_parameter_library
#include "cpcc2_tiago_parameters.hpp"

using namespace pinocchio;

namespace model_builder {

/// @brief Build a reduced model from a full model
/// @param urdf_path Path to the urdf file
/// @param joints Vector of the used joints names
Model build_model(std::string urdf_path, std::vector<std::string> joints);

void update_reduced_model(const Eigen::Ref<const Eigen::VectorXd> &x,
                          Model &model, Data &data);

SE3 get_end_effector_SE3(Data &data, FrameIndex &end_effector_id);
} // namespace model_builder

#endif // MODEL_BUILDER_HPP