cpcc2_tiago:

  joints: {
    type: string_array,
    default_value: [ arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint ], #it's very important for them to be ordered !
    description: "Name of the arm joints to control",
  }

  pveg_joints_command_type: {
    type: string_array,
    default_value: [ effort, effort, effort, effort, effort, effort, effort ],
    description: "Type of command to send to the joints",
  }

  state_interfaces_name: {
    type: string_array,
    default_value : [ position, velocity, effort ],
    description: "Name of the state interface",
  }

  end_effector: {
    type: string,
    default_value: "hand_tool_joint",
    description: "Name of the end effector joint",
  }

  OCP_horizon_length: {
    type: int,
    default_value: 20,
    description: "Horizon of the problem",
  }

  OCP_time_step: {
    type: double,
    default_value: 0.01,
    description: "OCP time step",
  }

  OCP_solver_iterations: {
    type: int,
    default_value: 1,
    description: "OCP iterations",
  }

  OCP_solver_frequency: {
    type: double,
    default_value: 100.0,
    description: "OCP solver frequency",
  }

  interpolation_type: {
    type: string,
    default_value: "aba",
    description: "Interpolation type, can be linear, aba or none",
  }

  enable_file_logging: {
    type: bool,
    default_value: false,
    description: "Enable logging",
  }

  log_folder: {
    type: string,
    default_value: "CPCC2_log/",
    description: "Log folder",
  }

  enable_live_logging: {
    type: bool,
    default_value: true,
    description: "Enable data stream to topic for plotjuggler",
  }
