cpcc2_tiago:
  joints: {
    type: string_array,
    default_value: [torso_lift_joint, arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint], #it's very important for them to be ordered !
    description: "Name of the arm joints to control",
  }
  pveg_joints_command_type: {
    type: string_array,
    default_value: [position, effort, effort, effort, effort, effort],
    description: "Type of command to send to the joints",
  }
  state_interfaces_name: {
    type: string_array,
    default_value : [position, velocity],
    description: "Name of the state interface",
  }
  arm_motors_static_friction: {
    type: double_array,
    default_value: [0, 0, 0, 0, 0, 0, 0, 0],
    description: "motors static friction coefficient",
  }
  arm_motors_viscous_friction: {
    type: double_array,
    default_value: [0, 0, 0, 0, 0, 0, 0, 0],
    description: "motors viscous friction coefficient",
  }
  arm_motors_K_tau: {
    type: double_array,
    default_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0],
    description: "motors K tau coefficient",
  }

  OCP_horizon_length: {
    type: int,
    default_value: 20,
    description: "Horizon of the problem",
  }

  OCP_time_step: {
    type: double,
    default_value: 0.05,
    description: "OCP time step",
  }

  OCP_solver_iterations: {
    type: int,
    default_value: 100,
    description: "OCP iterations",
  }

  OCP_solver_frequency: {
    type: double,
    default_value: 20.0,
    description: "OCP solver frequency",
  }

  enable_logging: {
    type: bool,
    default_value: false,
    description: "Enable logging",
  }

  log_file_path: {
    type: string,
    default_value: "/home/jgleyze/Desktop/logs/OCP_logger.csv",
    description: "Path to the log file",
  }

  logging_frequency: {
    type: double,
    default_value: 100.0,
    description: "Logging frequency",
  }


